protein=['Salmon','Tilapia','Pork Loin',"63 Degree Egg","Ahi Tuna","Albacore Tuna","Anchovy","Bacon Lardons",
"Basa","Beef Brisket","Beef Flank","Beef Flat Iron","Beef Jerky","Beef New York Strip","Beef Ribeye","Beef Sausage","Beef Shank",
"Beef Short Rib","Beef Sirloin","Beef Skirt","Beef Tenderloin","Bigeye Tuna","Black Cod","Blackfin Tuna","Blue Crab","Braised Beef",
"Braised Pork","Bratwurst","Bresaeola ","Brill","Butterfish","Canadian Bacon","Catfish","Chicken Breast","Chicken Liver",
"Chicken Tenders","Chicken Thigh","Clams","Cod","Confit Chicken","Crab","Crab Claws","Crawfish","Cuttlefish","Dorade",
"Duck Breast","Duck Confit","Duck Legs","Dungeoness Crab","Eel","Escargot","Flounder","Foie Gras","Fried Egg","Geoduck",
"Goose Breast","Ground Beef","Ground Pork","Grouper","Haddock","Halibut","Ham","Hard Boiled Egg","Herring","John Dory","King Crab",
"Lamb","Lamb Breast","Lamb Loin","Lamb Shank","Langostine","Lingcod","Lionfish","Liverwurst","Lobster","Mackerel","Monkfish",
"Mullet","Mussels","Octopus","Orange Roughy","Oysters","Pancetta","Parrotfish","Periwinkle","Pike","Poached Egg","Pork Belly",
"Pork Cheek","Pork Leg","Pork Loin","Pork Sausage","Pork Tenderloin","Quail Egg","Rabbit","Rabbit Loin","Rainbow Trout",
"Red Snapper","Redfish","Salami","Salmon","Scallops","Scrambled Egg","Sea Bass","Sea Bream","Shark","Shrimp","Skate","Smoked Bacon",
"Smoked Duck Leg","Smoked Turkey","Snapper","Snow Crab","Soft Boiled Egg","Squid","Striped Bass","Sturgeon","Sunny Side Up Egg",
"Surimi","Tilefish","Trout","Tuna","Turbot","Turkey Legs","Uni","Venison","Venison Loin","Wahoo","Whitefish","Yellowfin Tuna","Soft Tofu",
"Firm Tofu", "Goat"]

vegetable=["Beet","Acorn Squash","Alfalfa Sprouts","Amrud","Artichoke","Arugula","Asparagus","Aubergine (Eggplant)","Banana Squash",
"Bean Sprouts","Beet Greens (Chard)","Bell Pepper","Bitter Melon","Bok Choy","Broccoflower","Broccoli (Calabrese)",
"Brussels Sprouts","Butternut Squash","Cabbage","Carrot","Cauliflower","Celeriac","Celery","Chard (Beet Greens)",
"Chili Pepper","Chives","Collard Greens","Corn","Zucchini","Cucumber","Daikon","Delicata","Endive","Fennel",
"Fiddlehead Ferns","Frisee","Garlic","Gem Squash","Green Beans","Geens","Habanero","Horseradish","Jalapeño",
"Jerusalem Artichoke","Jicama","Kale","Kohlrabi","Leek","Lettuce","Mangel-Wurzel","Mung Beans","Mustard Greens",
"Nettles","Okra","Onion","Parsnip","Patty Pans","Peas","Potato","Pumpkin","Puandong","Radicchio","Radish","Rhubarb",
"Rutabaga","Salsify (Oyster Plant)","Scallion (Spring Onion UK, Green Onion US)","Shallot","Snap Peas","Soy Beans",
"Spaghetti Squash","Spinach","Split Peas","Squashes (biologically fruits, but taxed as vegetables)","sunchokes","Tat Soi",
"Tomato (biologically a fruit, but taxed as a vegetable)","Topinambur","Tubers","Turnip","Wasabi","Water Chestnut",
"Watercress","Rhite Radish"]

starch=["Acorn Squash","Azuki Beans (or Adzuki)","Barley","Black Beans","Black Eyed Peas","Black Lentils",
"Borlotti Bean","Bread","Broad Beans","Butternut Squash","Cannelini Beans","Cassava","Cous Cous","Farro Verde",
"Fingerling Potato","Fregola","Garbanzos","Israeli Cous Cous","Jasmine Rice","Jerusalem Artichoke","Kidney Beans",
"Legumes","Lentils","Lima Beans","Spaetzle","Long Grain Rice","Millet","Navy Beans","Oatmeal","Parsnip","Pasta","Pinto Beans",
"White Rice","Plantain","Polenta","Popcorn","Potato","Pumpkin","Quinoa","Red Lentils","Red Potato","Rice","Risotto",
"Runner Beans","Brown Rice","Russet Potato","Soy Beans","Steel Grind Oats","Sunchokes","Sushi Rice","Sweet Potato",
"Taro","Tubers","White Beans","Wild Rice","Yam","Yukon Gold Potato","Rice Noodles","Rice Paper","Dumpling",'Hominy']

sauce=['Gastrique',"Africaine","Agliata","Agrodulce","Aioli","Aji","Alfredo","Allemande","Arriabiata","Au Jus","Avocado Sauce",
"Balsamic Reduction","Barbecue Sauce","Bearnaise","Bechamel","Bercy","Beurre Blanc","Beurre Rouge","Bolognese","Bordelaise",
"Brasil Sauce","Budu","Buffalo Sauce","Caruso","Chancaca","Chasseur","Checca Sauce","Chermoula","Chimichurri","Choron",
"Citrus Vinaigrette","Cocktail Sauce","Dabu Dabu","Demi-Glace","Egusi Sauce","Espagnole","Foyot","Gochujang","Gravy",
"Gremolata","Gribiche","Guacamole","Hogao","Hoisin","Hollandaise","Honey Garlic Sauce","Honey Mustard","Ketchup","Kewpie Mayo",
"Lyonnaise","Maafe","Madeira","Maltaise","Marinara","Mayonaise","Mignonette","Moambe","Mole","Mornay","Mousseline","Mujdei",
"Nam Chim","Nam Phrik","Nantua","Normande","Nuoc Cham","Orange Glaze","Oyster Sauce","Peppercorn Sauce","Persillade","Pesto",
"Pico De Gallo","Plum Sauce","Ponzu","Poulette","Poutine","Puttanesca","Red Pepper Puree","Red Wine Reduction","Remoulade",
"Romesco","Saba","Sabayon","Salsa Rojo","Salsa Verde","Sambal","Satay Sauce","Sauce Vierge","Sofrito","Soubise",
"Soy Sauce","Sriracha","Ssamjang","Sugo","Supreme","Sweet Bean Sauce","Sweet Chili Sauce","Tartar Sauce","Tentsuyu",
"Teriyaki","Tkemali","Tomato Sauce","Tonkatsu","Toum","Umeboshi","Venetian Sauce","Vin Blanc","Vodka Sauce",
"Worchestershire Sauce","XO Sauce","Yogurt","Creme Fraiche"]

garnish=['Cilantro','Fried Leek Threads','Fried Parsnip','Thyme',"Allspice","Almond","Anise","Annatto/Achiote","Basil","Bay Leaf","Beetroot","Black Cardamom",
"Bonito (Katsuobushi)","Brunoise","Cacao","Cardamom","Caroway","Cayenne pepper","Celery Seed","Chamomile","Chia Seed","Chile",
"Chive","Chocolate","Cilantro","Cinnamon","Citrus","Citrus Zest","Clove","Coriander","Crouton","Cumin","Curry Leaf","Dill","Epazote",
"Fennel","Fenugreek","File Powder","Fried Garlic","Fried Onions","Fried Shallots","Galangal","Garlic","ginger","Grains of Paradise",
"Green Onion","Harissa","Honey","Horseradish","Hungarian Paprika","Juniper","Kaffir Lime","Lavender","Lemon","Lemongrass","Lettuce",
"Lime","Long Pepper","Lovage","Malheb","Maple Syrup","Marjoram","Mase","Mexican Oregano","Mint","Mint","Mustard","Nigella Sativa",
"Onion","Orange","Oregano","Paprika","Parsley","Poppy Seed","Porcini Powder","Profiteroles","Rose Petals","Rosemary","Royale","Sage",
"Savory","Shallot","Shiitake","Smoke (applewood)","Smoke (cherry)","Smoke (hickory)","Smoke (mesquite)","Smoke (oak)","Smoked Paprika",
"Sorrel","Star Anise","Sumac","Tabasco pepper","Terragon","Thyme","Turmeric","Vanilla","Caviar","Salmon Roe (ikura)",
"Capelin Roe (masago)","Flying fish roe (tobiko)","Blood Orange","Kombu","Parmesan","Bottarga","Nori","Togarashi"]

